name: Build and Push Docker Image to ECR

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Select ECR repository'
        required: true
        type: choice
        options:
          - streamlit/production
          - streamlit/staging

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.ECR_REGISTRY }}/${{ github.event.inputs.repository }}:latest
            ${{ secrets.ECR_REGISTRY }}/${{ github.event.inputs.repository }}:${{ github.sha }}
